changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: New Features
      labels:
        - enhancement
        - semver-minor
    - title: Other Changes
      labels:
        - "*"
