schema = 3

[mod]
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.32.4"
    hash = "sha256-mGONd4wmBmM69NFuxAINHcHzb8M9dRo49Zv2iJFZGhw="
  [mod."github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream"]
    version = "v1.6.6"
    hash = "sha256-MS6ptFmzCteXGCSWI3rxiLOgSVxwzJHw/jGAaU1L0tw="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.28.1"
    hash = "sha256-ofYaPOpi1CbEJBLa7OL5AIZP9Tebddet4BwvozMDGqE="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.17.42"
    hash = "sha256-5/SBK/2cW3Nsg1lwLtQFIIoVpZXkR2WKq7fDgvaMTNc="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.16.18"
    hash = "sha256-YYEQzgcnxSP5pmRvfbdQ6Jio2EvFSkxeYsq8YeCGgeE="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.3.23"
    hash = "sha256-OCOH5LeaRyzLo/0n1pILGix/QKzj8vM7U1A/oU/0gj8="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.6.23"
    hash = "sha256-ndWnFojsHWtZhaAT1Wy18+0z80MSuL3Pil9HWWKPpMM="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.8.1"
    hash = "sha256-xinXoaSTaE4p/Li9h3nE8t7Y0uM6OFX/qkS+sCHQtp4="
  [mod."github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"]
    version = "v1.43.0"
    hash = "sha256-AY8cCOgJ7D2IxuuLbo6uNKYhWeFvML2dG9NCAI6SJ2g="
  [mod."github.com/aws/aws-sdk-go-v2/service/ecs"]
    version = "v1.49.0"
    hash = "sha256-nUUkFdeUpJ0N2Ehyb8yexyDoWACyRxHpsWFxeQwWQZk="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.12.0"
    hash = "sha256-ARkJfcecbLOyQhdQHsp8NA408L5/wLxEyVtC+Mh676Y="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.12.3"
    hash = "sha256-Xk++VAqIhxr2PQYqcM+rhLpeXB8Q7UAo7CZVV7Zcwsg="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssm"]
    version = "v1.55.5"
    hash = "sha256-zYUbAC91wDeQ8yOwTGcv2Ac41QXrlk+J0+brB0SVQuw="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.24.3"
    hash = "sha256-LAhY2PktkFFYYiPwaec/q5BWTv1UUWpQVRyHxBfK1z4="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.28.3"
    hash = "sha256-NbSGL9Zb8RFYloUXCfRIf0JKiTchTZclW+pFkSotJP4="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.32.3"
    hash = "sha256-H4Ew6RuU/6Sb56BlWGBr1mOaTK7FO6jWMqvbwjO+yww="
  [mod."github.com/aws/smithy-go"]
    version = "v1.22.0"
    hash = "sha256-dowFXJpYD5fpUNDJMZvIQzjN8qc9ppqw7j8wrQdfK/U="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/catppuccin/go"]
    version = "v0.2.0"
    hash = "sha256-/MZXZD/WlVh75ruSOnq+HlMVNz9vMfpaTIXT//CZU4k="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.20.0"
    hash = "sha256-p5jmxDfH9vEWsafg1lB7HBTUSysXrTGymTThFYClrOE="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v1.1.0"
    hash = "sha256-LPOpM47jiLV+FBvDp3Ry4HXQMZOCSeJTWe22w4KL35A="
  [mod."github.com/charmbracelet/colorprofile"]
    version = "v0.2.3-0.20250311203215-f60798e515dc"
    hash = "sha256-D9E/bMOyLXAUVOHA1/6o3i+vVmLfwIMOWib6sU7A6+Q="
  [mod."github.com/charmbracelet/huh"]
    version = "v0.6.0"
    hash = "sha256-Pky6gyJNZkk3gYbVm2wngz1FJHgDeFSwI3KupuMKMWg="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v1.1.0"
    hash = "sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.8.0"
    hash = "sha256-/YyDkGrULV2BtnNk3ojeSl0nUWQwIfIdW7WJuGbAZas="
  [mod."github.com/charmbracelet/x/cellbuf"]
    version = "v0.0.13-0.20250311204145-2c3ea96c31dd"
    hash = "sha256-XAhCOt8qJ2vR77lH1ez0IVU1/2CaLTq9jSmrHVg5HHU="
  [mod."github.com/charmbracelet/x/exp/strings"]
    version = "v0.0.0-20240722160745-212f7b056ed0"
    hash = "sha256-NWe8LHXUtrrABWFhmAzLNYAZyJIwN3C/T2OdaInjl9E="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.1"
    hash = "sha256-VBkCZLI90PhMasftGw3403IqoV7d3E5WEGAIVrN5xQM="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/erikgeiser/coninput"]
    version = "v0.0.0-20211004153227-1c3628e74d0f"
    hash = "sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.16"
    hash = "sha256-NC+ntvwIpqDNmXb7aixcg09il80ygq6JAnW0Gb5b/DQ="
  [mod."github.com/mitchellh/hashstructure/v2"]
    version = "v2.0.2"
    hash = "sha256-O4Yw4pPQECWe8DoVDIH2nUMN8Zl8waS7/O1sv18M2Xs="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20230316100256-276c6243b2f6"
    hash = "sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/termenv"]
    version = "v0.16.0"
    hash = "sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.1"
    hash = "sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.30.0"
    hash = "sha256-BuhWtwDkciVioc03rxty6G2vcZVnPX85lI7tgQOFVP8="
  [mod."golang.org/x/text"]
    version = "v0.18.0"
    hash = "sha256-aNvJW4gQs+MTfdz6DZqyyHQS2GJ9W8L8qKPVODPn4+k="
