schema = 3

[mod]
  [mod."atomicgo.dev/cursor"]
    version = "v0.2.0"
    hash = "sha256-ukCb15fSgbkkYdzYY7dIq+HQqZvlpR5MytK20bwtSDc="
  [mod."atomicgo.dev/keyboard"]
    version = "v0.2.9"
    hash = "sha256-TqZY8yzAs9vEVR9dSi8yxBUIKPB875B2jl8fFGXQsCs="
  [mod."atomicgo.dev/schedule"]
    version = "v0.1.0"
    hash = "sha256-dBu76Ez+1S+koYL8KITrT/iEUN4U+8mk3BI/JZOr+Y8="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.32.4"
    hash = "sha256-mGONd4wmBmM69NFuxAINHcHzb8M9dRo49Zv2iJFZGhw="
  [mod."github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream"]
    version = "v1.6.6"
    hash = "sha256-MS6ptFmzCteXGCSWI3rxiLOgSVxwzJHw/jGAaU1L0tw="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.28.1"
    hash = "sha256-ofYaPOpi1CbEJBLa7OL5AIZP9Tebddet4BwvozMDGqE="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.17.42"
    hash = "sha256-5/SBK/2cW3Nsg1lwLtQFIIoVpZXkR2WKq7fDgvaMTNc="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.16.18"
    hash = "sha256-YYEQzgcnxSP5pmRvfbdQ6Jio2EvFSkxeYsq8YeCGgeE="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.3.23"
    hash = "sha256-OCOH5LeaRyzLo/0n1pILGix/QKzj8vM7U1A/oU/0gj8="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.6.23"
    hash = "sha256-ndWnFojsHWtZhaAT1Wy18+0z80MSuL3Pil9HWWKPpMM="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.8.1"
    hash = "sha256-xinXoaSTaE4p/Li9h3nE8t7Y0uM6OFX/qkS+sCHQtp4="
  [mod."github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"]
    version = "v1.43.0"
    hash = "sha256-AY8cCOgJ7D2IxuuLbo6uNKYhWeFvML2dG9NCAI6SJ2g="
  [mod."github.com/aws/aws-sdk-go-v2/service/ecs"]
    version = "v1.49.0"
    hash = "sha256-nUUkFdeUpJ0N2Ehyb8yexyDoWACyRxHpsWFxeQwWQZk="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.12.0"
    hash = "sha256-ARkJfcecbLOyQhdQHsp8NA408L5/wLxEyVtC+Mh676Y="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.12.3"
    hash = "sha256-Xk++VAqIhxr2PQYqcM+rhLpeXB8Q7UAo7CZVV7Zcwsg="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssm"]
    version = "v1.55.5"
    hash = "sha256-zYUbAC91wDeQ8yOwTGcv2Ac41QXrlk+J0+brB0SVQuw="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.24.3"
    hash = "sha256-LAhY2PktkFFYYiPwaec/q5BWTv1UUWpQVRyHxBfK1z4="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.28.3"
    hash = "sha256-NbSGL9Zb8RFYloUXCfRIf0JKiTchTZclW+pFkSotJP4="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.32.3"
    hash = "sha256-H4Ew6RuU/6Sb56BlWGBr1mOaTK7FO6jWMqvbwjO+yww="
  [mod."github.com/aws/smithy-go"]
    version = "v1.22.0"
    hash = "sha256-dowFXJpYD5fpUNDJMZvIQzjN8qc9ppqw7j8wrQdfK/U="
  [mod."github.com/containerd/console"]
    version = "v1.0.3"
    hash = "sha256-4p4u/rS7G4KKbIcZaVMqE1OtSoNlOpmcYFwO0ZEH/V0="
  [mod."github.com/gookit/color"]
    version = "v1.5.4"
    hash = "sha256-6Xydefyslup+qohzatAdezGWrS065X5mx18wvRef3Rk="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/lithammer/fuzzysearch"]
    version = "v1.1.8"
    hash = "sha256-aMMRcrlUc9CBiiNkcnWWn4hfNMNyVhrAt67kvP4D4Do="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.15"
    hash = "sha256-WP39EU2UrQbByYfnwrkBDoKN7xzXsBssDq3pNryBGm0="
  [mod."github.com/pterm/pterm"]
    version = "v0.12.79"
    hash = "sha256-c+cuXa9qS4bQ7lsvYHA6bBLwE7n3j6g3yiglwbgnbHc="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.4"
    hash = "sha256-B8tbL9K6ICLdm0lEhs9+h4cpjAfvFtNiFMGvQZmw0bM="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.1"
    hash = "sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."golang.org/x/sys"]
    version = "v0.16.0"
    hash = "sha256-ZkGclbp2S7NQYhbuGji6XokCn2Qi1BJy8dwyAOTV8sY="
  [mod."golang.org/x/term"]
    version = "v0.16.0"
    hash = "sha256-9qlHcsCI1sa7ZI4Q+fJbOp3mG5Y+uV16e+pGmG+MQe0="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
