[project]
name = "iecs"
revision = "1.0"

[profiles.default]
GEMINI_API_KEY = { description = "Google Gemini API key", required = false }

[profiles.development]
# Development profile inherits all secrets from default profile
# Only define secrets here that need different values or settings than default
