name: CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv
        run: nix profile install nixpkgs#devenv
      - name: Install dependencies
        run: devenv shell -- true
      - uses: swatinem/rust-cache@v2
      - name: Compile code
        run: devenv shell -- cargo check
      - name: Run checks
        run: devenv test
